### ISSUE TITLE
URDF exporter not running

### ISSUE THREAD

**Issue by EngineerSte** [yanshil/Fusion2PyBullet#1]
Hi, 

This looks like a great tool. One issue I have is that it will not run. No error message or anything. I have tried both this version also the stable version. And i have tried it on a simple 4DOF legged robot and also a simple box. The graphwiz does work the the tree structure looks good as far as I can tell. 

This is the text output:

digraph G {  "base_link" -> "leg_v21leg1" [ label = "Rev1" ] 
  "base_link" -> "leg_v22leg1" [ label = "Rev2" ] 
  "base_link" -> "leg_v23leg1" [ label = "Rev3" ] 
  "base_link" -> "leg_v24leg1" [ label = "Rev4" ] 
}

I ensured I have no nested components and that my base_link is called base_link. 

Do you have any suggestions on how I might get it to work?

Thanks, 
Stephen

**Comment by yanshil** [comment]
When a script in Fusion 360 not run at all, there must be some bug in it. But since I don't have your project I can't tell what happens.

There are three things you can try:
1. If you are familiar with VS code, you can debug the project within the Fusion360
![](https://github.com/yanshil/Fusion2PyBullet/raw/master/imgs/6_debug.PNG)
2. I build from this repo. You https://github.com/syuntoku14/fusion2urdf. You can try this version to see will it works
3. If the debug mode still show nothing, you can share a working demo with me. I will take a look at it.
